<?php

$root = dirname(__DIR__);

$base = [
    'DigiTexia | Projects and Digital Infrastructure Portfolio' => [
        'es' => 'DigiTexia | Proyectos y portafolio de infraestructura digital',
        'it' => 'DigiTexia | Progetti e portfolio di infrastruttura digitale',
        'zh' => 'DigiTexia | 项目与数字基础设施作品集',
    ],
    'FLAGSHIP / AQUAWATCH AI' => ['es' => 'INSIGNIA / AQUAWATCH AI', 'it' => 'PRINCIPALE / AQUAWATCH AI', 'zh' => '旗舰 / AQUAWATCH AI'],
    'An AI-powered water monitoring and operational intelligence platform.' => ['es' => 'Una plataforma de monitoreo del agua e inteligencia operativa impulsada por IA.', 'it' => 'Una piattaforma di monitoraggio idrico e intelligenza operativa basata su IA.', 'zh' => '一个由 AI 驱动的水务监测与运营智能平台。'],
    'Water infrastructure is hard to monitor manually, so losses and failures go undetected too long.' => ['es' => 'La infraestructura de agua es dificil de monitorear manualmente, por lo que perdidas y fallas pasan desapercibidas demasiado tiempo.', 'it' => 'L infrastruttura idrica e difficile da monitorare manualmente, quindi perdite e guasti restano inosservati troppo a lungo.', 'zh' => '水务基础设施难以手工监测，因此损耗和故障会长期未被发现。'],
    'Utilities and organizations managing water infrastructure.' => ['es' => 'Servicios publicos y organizaciones que gestionan infraestructura de agua.', 'it' => 'Utility e organizzazioni che gestiscono infrastrutture idriche.', 'zh' => '管理水务基础设施的公共服务机构和组织。'],
    'Improved resource management and faster, better-informed decisions.' => ['es' => 'Mejor gestion de recursos y decisiones mas rapidas y mejor informadas.', 'it' => 'Migliore gestione delle risorse e decisioni piu rapide e informate.', 'zh' => '改善资源管理，并实现更快、更充分的信息化决策。'],
    'Applies AI-driven monitoring to infrastructure that has long relied on manual inspection.' => ['es' => 'Aplica monitoreo impulsado por IA a infraestructuras que durante mucho tiempo dependieron de inspeccion manual.', 'it' => 'Applica monitoraggio basato su IA a infrastrutture che hanno a lungo fatto affidamento su ispezioni manuali.', 'zh' => '将 AI 驱动监测应用于长期依赖人工巡检的基础设施。'],
    'FLAGSHIP / WASTEPAY' => ['es' => 'INSIGNIA / WASTEPAY', 'it' => 'PRINCIPALE / WASTEPAY', 'zh' => '旗舰 / WASTEPAY'],
    'A smart waste management system using QR tracking and recycling incentives.' => ['es' => 'Un sistema inteligente de gestion de residuos con seguimiento QR e incentivos de reciclaje.', 'it' => 'Un sistema intelligente di gestione rifiuti con tracciamento QR e incentivi al riciclo.', 'zh' => '使用二维码追踪和回收激励的智能废弃物管理系统。'],
    'Waste collection and recycling programs lack reliable traceability and incentive structures.' => ['es' => 'Los programas de recoleccion y reciclaje carecen de trazabilidad confiable y estructuras de incentivo.', 'it' => 'I programmi di raccolta e riciclo mancano di tracciabilita affidabile e strutture di incentivo.', 'zh' => '废弃物收集和回收项目缺乏可靠追溯和激励结构。'],
    'Municipalities, waste operators, NGOs and circular economy initiatives.' => ['es' => 'Municipios, operadores de residuos, ONG e iniciativas de economia circular.', 'it' => 'Comuni, operatori dei rifiuti, ONG e iniziative di economia circolare.', 'zh' => '市政机构、废弃物运营商、NGO 和循环经济项目。'],
    'Verified waste flows, stronger citizen participation and clearer operational reporting.' => ['es' => 'Flujos de residuos verificados, mayor participacion ciudadana y reporting operativo mas claro.', 'it' => 'Flussi di rifiuti verificati, maggiore partecipazione dei cittadini e reporting operativo piu chiaro.', 'zh' => '经验证的废弃物流、更强的公众参与和更清晰的运营报告。'],
    'Connects field collection, QR verification and incentive logic in one digital workflow.' => ['es' => 'Conecta recoleccion en campo, verificacion QR y logica de incentivos en un flujo digital.', 'it' => 'Collega raccolta sul campo, verifica QR e logica incentivi in un unico workflow digitale.', 'zh' => '将现场收集、二维码验证和激励逻辑连接到一个数字工作流。'],
    'FLAGSHIP / CARBON AFRICA EXCHANGE' => ['es' => 'INSIGNIA / CARBON AFRICA EXCHANGE', 'it' => 'PRINCIPALE / CARBON AFRICA EXCHANGE', 'zh' => '旗舰 / CARBON AFRICA EXCHANGE'],
    'Carbon tracking and marketplace infrastructure for climate programs.' => ['es' => 'Infraestructura de seguimiento de carbono y mercado para programas climaticos.', 'it' => 'Infrastruttura di tracciamento carbonio e marketplace per programmi climatici.', 'zh' => '面向气候项目的碳追踪与市场基础设施。'],
    'Forest, agriculture and carbon data are difficult to structure, verify and monetize responsibly.' => ['es' => 'Los datos forestales, agricolas y de carbono son dificiles de estructurar, verificar y monetizar responsablemente.', 'it' => 'Dati forestali, agricoli e carbonio sono difficili da strutturare, verificare e monetizzare responsabilmente.', 'zh' => '森林、农业和碳数据难以负责任地结构化、验证和变现。'],
    'Climate programs, land projects, development agencies and ESG teams.' => ['es' => 'Programas climaticos, proyectos de tierra, agencias de desarrollo y equipos ESG.', 'it' => 'Programmi climatici, progetti territoriali, agenzie di sviluppo e team ESG.', 'zh' => '气候项目、土地项目、发展机构和 ESG 团队。'],
    'Structured carbon intelligence and a foundation for trusted carbon credit workflows.' => ['es' => 'Inteligencia de carbono estructurada y base para flujos confiables de creditos de carbono.', 'it' => 'Intelligenza carbonio strutturata e base per workflow affidabili di crediti di carbonio.', 'zh' => '结构化碳智能，以及可信碳信用工作流的基础。'],
    'Builds climate data infrastructure designed for African territory realities.' => ['es' => 'Construye infraestructura de datos climaticos disenada para las realidades territoriales africanas.', 'it' => 'Costruisce infrastruttura dati climatici progettata per le realta territoriali africane.', 'zh' => '构建面向非洲地域现实的气候数据基础设施。'],
    'FLAGSHIP / DIGITAL TWIN PLATFORM' => ['es' => 'INSIGNIA / DIGITAL TWIN PLATFORM', 'it' => 'PRINCIPALE / DIGITAL TWIN PLATFORM', 'zh' => '旗舰 / DIGITAL TWIN PLATFORM'],
    'A territorial intelligence layer for infrastructure, services and field data.' => ['es' => 'Una capa de inteligencia territorial para infraestructura, servicios y datos de campo.', 'it' => 'Un livello di intelligenza territoriale per infrastrutture, servizi e dati sul campo.', 'zh' => '面向基础设施、服务和现场数据的区域智能层。'],
    'Governments and institutions lack real-time intelligence across distributed infrastructure.' => ['es' => 'Gobiernos e instituciones carecen de inteligencia en tiempo real sobre infraestructura distribuida.', 'it' => 'Governi e istituzioni mancano di intelligence in tempo reale su infrastrutture distribuite.', 'zh' => '政府和机构缺乏跨分布式基础设施的实时智能。'],
    'Governments, cities, NGOs and infrastructure operators.' => ['es' => 'Gobiernos, ciudades, ONG y operadores de infraestructura.', 'it' => 'Governi, citta, ONG e operatori infrastrutturali.', 'zh' => '政府、城市、NGO 和基础设施运营商。'],
    'Better planning, live monitoring and data-backed public decisions.' => ['es' => 'Mejor planificacion, monitoreo en vivo y decisiones publicas respaldadas por datos.', 'it' => 'Migliore pianificazione, monitoraggio live e decisioni pubbliche basate sui dati.', 'zh' => '更好的规划、实时监测和数据支持的公共决策。'],
    'Turns fragmented field data into a digital nervous system for territories.' => ['es' => 'Convierte datos de campo fragmentados en un sistema nervioso digital para territorios.', 'it' => 'Trasforma dati di campo frammentati in un sistema nervoso digitale per i territori.', 'zh' => '将碎片化现场数据转化为区域的数字神经系统。'],
    'CLIENT / GOVERNMENT' => ['es' => 'CLIENTE / GOBIERNO', 'it' => 'CLIENTE / GOVERNO', 'zh' => '客户 / 政府'],
    'A national digital platform connecting Cameroonian youth to opportunity.' => ['es' => 'Una plataforma digital nacional que conecta a la juventud camerunesa con oportunidades.', 'it' => 'Una piattaforma digitale nazionale che collega i giovani camerunesi alle opportunita.', 'zh' => '连接喀麦隆青年与机会的国家数字平台。'],
    'No centralized digital platform existed to connect youth with government programs and opportunities.' => ['es' => 'No existia una plataforma digital centralizada para conectar a los jovenes con programas y oportunidades gubernamentales.', 'it' => 'Non esisteva una piattaforma digitale centralizzata per collegare i giovani a programmi e opportunita governative.', 'zh' => '此前没有集中式数字平台将青年与政府项目和机会连接起来。'],
    'Build a modern, scalable public platform reflecting national identity and government standards.' => ['es' => 'Construir una plataforma publica moderna y escalable que refleje la identidad nacional y los estandares gubernamentales.', 'it' => 'Costruire una piattaforma pubblica moderna e scalabile che rifletta identita nazionale e standard governativi.', 'zh' => '构建体现国家身份和政府标准的现代可扩展公共平台。'],
    'An accessible digital front door connecting youth across Cameroon to opportunity, on infrastructure ready to scale nationally.' => ['es' => 'Una puerta digital accesible que conecta a jovenes de Camerun con oportunidades, sobre infraestructura lista para escalar nacionalmente.', 'it' => 'Una porta digitale accessibile che collega i giovani del Camerun alle opportunita, su infrastruttura pronta a scalare a livello nazionale.', 'zh' => '一个可访问的数字入口，将喀麦隆各地青年与机会连接起来，并具备全国扩展能力。'],
    'CLIENT / FINANCIAL SERVICES' => ['es' => 'CLIENTE / SERVICIOS FINANCIEROS', 'it' => 'CLIENTE / SERVIZI FINANZIARI', 'zh' => '客户 / 金融服务'],
    'A tailored Performia deployment for a regulated financial institution.' => ['es' => 'Un despliegue Performia adaptado para una institucion financiera regulada.', 'it' => 'Un deployment Performia su misura per un istituto finanziario regolamentato.', 'zh' => '为受监管金融机构定制部署的 Performia。'],
    'Manual performance tracking limited visibility into staff execution and KPIs.' => ['es' => 'El seguimiento manual del rendimiento limitaba la visibilidad sobre ejecucion del personal y KPIs.', 'it' => 'Il tracciamento manuale delle prestazioni limitava la visibilita su esecuzione del personale e KPI.', 'zh' => '手工绩效跟踪限制了员工执行和 KPI 的可见性。'],
    'Deploy a performance management platform tailored to the institution operating model.' => ['es' => 'Desplegar una plataforma de gestion del rendimiento adaptada al modelo operativo de la institucion.', 'it' => 'Distribuire una piattaforma di gestione prestazioni adattata al modello operativo dell istituzione.', 'zh' => '部署适应该机构运营模型的绩效管理平台。'],
    'Real-time performance visibility and structured, auditable workforce management.' => ['es' => 'Visibilidad de rendimiento en tiempo real y gestion laboral estructurada y auditable.', 'it' => 'Visibilita prestazioni in tempo reale e gestione del personale strutturata e auditabile.', 'zh' => '实时绩效可见性和结构化、可审计的员工管理。'],
    'CLIENT / PROFESSIONAL ASSOCIATION' => ['es' => 'CLIENTE / ASOCIACION PROFESIONAL', 'it' => 'CLIENTE / ASSOCIAZIONE PROFESSIONALE', 'zh' => '客户 / 专业协会'],
    'A modernized digital identity for a national professional association.' => ['es' => 'Una identidad digital modernizada para una asociacion profesional nacional.', 'it' => 'Un identita digitale modernizzata per un associazione professionale nazionale.', 'zh' => '面向国家级专业协会的现代化数字身份。'],
    'An outdated digital presence weakened the association credibility with members and partners.' => ['es' => 'Una presencia digital obsoleta debilitaba la credibilidad de la asociacion ante miembros y socios.', 'it' => 'Una presenza digitale obsoleta indeboliva la credibilita dell associazione presso membri e partner.', 'zh' => '过时的数字形象削弱了协会在会员和伙伴中的可信度。'],
    'A refreshed digital presence that strengthens credibility with members, partners and the public.' => ['es' => 'Una presencia digital renovada que fortalece la credibilidad ante miembros, socios y publico.', 'it' => 'Una presenza digitale rinnovata che rafforza la credibilita presso membri, partner e pubblico.', 'zh' => '焕新的数字形象，增强会员、伙伴和公众的信任。'],
    'CLIENT / ENTERPRISE' => ['es' => 'CLIENTE / EMPRESA', 'it' => 'CLIENTE / IMPRESA', 'zh' => '客户 / 企业'],
    'A cleaner digital presentation for an enterprise brand and its stakeholders.' => ['es' => 'Una presentacion digital mas clara para una marca empresarial y sus partes interesadas.', 'it' => 'Una presentazione digitale piu chiara per un brand aziendale e i suoi stakeholder.', 'zh' => '面向企业品牌及其利益相关方的更清晰数字展示。'],
    'The brand needed a clearer online presentation aligned with its business credibility.' => ['es' => 'La marca necesitaba una presentacion online mas clara, alineada con su credibilidad empresarial.', 'it' => 'Il brand aveva bisogno di una presentazione online piu chiara, allineata alla sua credibilita aziendale.', 'zh' => '该品牌需要更清晰的线上呈现，以匹配其商业可信度。'],
    'Improve structure, visual hierarchy and access to key company information.' => ['es' => 'Mejorar estructura, jerarquia visual y acceso a informacion clave de la empresa.', 'it' => 'Migliorare struttura, gerarchia visiva e accesso alle informazioni chiave aziendali.', 'zh' => '改善结构、视觉层级和关键公司信息的访问。'],
    'A more professional digital experience for prospects, partners and stakeholders.' => ['es' => 'Una experiencia digital mas profesional para prospectos, socios y partes interesadas.', 'it' => 'Un esperienza digitale piu professionale per prospect, partner e stakeholder.', 'zh' => '为潜在客户、合作伙伴和利益相关方提供更专业的数字体验。'],
    'Secure, auditable systems for regulated institutions.' => ['es' => 'Sistemas seguros y auditables para instituciones reguladas.', 'it' => 'Sistemi sicuri e auditabili per istituzioni regolamentate.', 'zh' => '面向受监管机构的安全、可审计系统。'],
    'Traceability and identity infrastructure for patient safety.' => ['es' => 'Infraestructura de trazabilidad e identidad para la seguridad del paciente.', 'it' => 'Infrastruttura di tracciabilita e identita per la sicurezza del paziente.', 'zh' => '面向患者安全的追溯与身份基础设施。'],
    'Water Utilities' => ['es' => 'Servicios de agua', 'it' => 'Servizi idrici', 'zh' => '水务机构'],
    'Monitoring and intelligence for critical infrastructure.' => ['es' => 'Monitoreo e inteligencia para infraestructura critica.', 'it' => 'Monitoraggio e intelligenza per infrastrutture critiche.', 'zh' => '面向关键基础设施的监测与智能。'],
    'Transparent, scalable platforms for public institutions.' => ['es' => 'Plataformas transparentes y escalables para instituciones publicas.', 'it' => 'Piattaforme trasparenti e scalabili per istituzioni pubbliche.', 'zh' => '面向公共机构的透明、可扩展平台。'],
    'Accountable digital tools built for constrained budgets.' => ['es' => 'Herramientas digitales responsables construidas para presupuestos limitados.', 'it' => 'Strumenti digitali responsabili costruiti per budget vincolati.', 'zh' => '面向有限预算构建的可追责数字工具。'],
    'A portfolio of digital solutions built to solve real operational challenges.' => ['es' => 'Un portafolio de soluciones digitales creado para resolver desafios operativos reales.', 'it' => 'Un portfolio di soluzioni digitali costruito per risolvere sfide operative reali.', 'zh' => '为解决真实运营挑战而构建的数字解决方案作品集。'],
    'From proprietary products to tailored enterprise platforms, every DigiTexia project reflects the same discipline: engineering excellence in service of measurable business impact.' => ['es' => 'Desde productos propios hasta plataformas empresariales a medida, cada proyecto DigiTexia refleja la misma disciplina: excelencia de ingenieria al servicio de impacto empresarial medible.', 'it' => 'Dai prodotti proprietari alle piattaforme enterprise su misura, ogni progetto DigiTexia riflette la stessa disciplina: eccellenza ingegneristica al servizio di impatto business misurabile.', 'zh' => '从自有产品到定制企业平台，每个 DigiTexia 项目都体现同一原则：以工程卓越服务可衡量的业务影响。'],
    'We build proprietary products and tailored enterprise solutions, and hold both to the same standard.' => ['es' => 'Construimos productos propios y soluciones empresariales a medida, y exigimos el mismo estandar a ambos.', 'it' => 'Costruiamo prodotti proprietari e soluzioni enterprise su misura, mantenendo entrambi allo stesso standard.', 'zh' => '我们构建自有产品和定制企业解决方案，并以同一标准要求两者。'],
    'Every project starts from a real operational need, not a technology looking for a use case. Whether we deploy a proven product or engineer a custom platform, the objective is the same: infrastructure designed to deliver long-term value.' => ['es' => 'Cada proyecto parte de una necesidad operativa real, no de una tecnologia buscando caso de uso. Ya sea un producto probado o una plataforma a medida, el objetivo es el mismo: infraestructura disenada para entregar valor a largo plazo.', 'it' => 'Ogni progetto nasce da una reale esigenza operativa, non da una tecnologia in cerca di caso d uso. Che distribuiamo un prodotto provato o progettiamo una piattaforma su misura, l obiettivo e lo stesso: infrastruttura progettata per valore a lungo termine.', 'zh' => '每个项目都始于真实运营需求，而不是寻找用例的技术。无论部署成熟产品还是工程化定制平台，目标一致：交付长期价值的基础设施。'],
    'Proprietary digital products, deployed and proven' => ['es' => 'Productos digitales propios, desplegados y probados', 'it' => 'Prodotti digitali proprietari, distribuiti e comprovati', 'zh' => '已部署并验证的自有数字产品'],
    'Four platforms engineered for critical infrastructure challenges across Africa.' => ['es' => 'Cuatro plataformas disenadas para desafios de infraestructura critica en Africa.', 'it' => 'Quattro piattaforme progettate per sfide di infrastruttura critica in Africa.', 'zh' => '面向非洲关键基础设施挑战工程化的四个平台。'],
    'Custom platforms, built around real business transformation' => ['es' => 'Plataformas a medida, construidas alrededor de transformacion empresarial real', 'it' => 'Piattaforme su misura, costruite intorno a una reale trasformazione business', 'zh' => '围绕真实业务转型构建的定制平台'],
    'Beyond our own products, we engineer bespoke digital infrastructure for organizations with specific operational requirements.' => ['es' => 'Mas alla de nuestros productos, disenamos infraestructura digital a medida para organizaciones con requisitos operativos especificos.', 'it' => 'Oltre ai nostri prodotti, progettiamo infrastruttura digitale su misura per organizzazioni con requisiti operativi specifici.', 'zh' => '除自有产品外，我们还为有特定运营需求的组织工程化定制数字基础设施。'],
    'Innovation is not a department. It is how we work.' => ['es' => 'La innovacion no es un departamento. Es nuestra forma de trabajar.', 'it' => 'L innovazione non e un reparto. E il modo in cui lavoriamo.', 'zh' => '创新不是一个部门，而是我们的工作方式。'],
    'Portfolio experience across Africa strategic sectors' => ['es' => 'Experiencia de portafolio en sectores estrategicos de Africa', 'it' => 'Esperienza di portfolio nei settori strategici africani', 'zh' => '覆盖非洲战略行业的项目经验'],
    'Every project deepens our understanding of the operational realities specific to each industry.' => ['es' => 'Cada proyecto profundiza nuestra comprension de las realidades operativas propias de cada industria.', 'it' => 'Ogni progetto approfondisce la nostra comprensione delle realta operative specifiche di ogni settore.', 'zh' => '每个项目都加深我们对各行业运营现实的理解。'],
    'Let us design your next digital solution' => ['es' => 'Disenemos su proxima solucion digital', 'it' => 'Progettiamo la vostra prossima soluzione digitale', 'zh' => '让我们设计您的下一个数字解决方案'],
    'Every project in this portfolio started with a conversation about a real operational challenge.' => ['es' => 'Cada proyecto de este portafolio comenzo con una conversacion sobre un desafio operativo real.', 'it' => 'Ogni progetto in questo portfolio e iniziato con una conversazione su una reale sfida operativa.', 'zh' => '此作品集中的每个项目都始于一次关于真实运营挑战的对话。'],
    'If your organization is facing one, we can discuss it and share how a similar solution might apply to your context.' => ['es' => 'Si su organizacion enfrenta uno, podemos conversarlo y compartir como una solucion similar podria aplicarse a su contexto.', 'it' => 'Se la vostra organizzazione ne affronta una, possiamo discuterne e condividere come una soluzione simile potrebbe applicarsi al vostro contesto.', 'zh' => '如果您的组织正面临类似问题，我们可以讨论并分享类似方案如何适用于您的场景。'],
    "Modernize the organization's digital identity to reflect its role and standing." => ['es' => 'Modernizar la identidad digital de la organizacion para reflejar su rol y posicion.', 'it' => 'Modernizzare l identita digitale dell organizzazione per rifletterne ruolo e posizionamento.', 'zh' => '现代化组织的数字身份，以体现其角色和地位。'],
    "DigiTexia continuously invests in innovation to build digital solutions that address Africa's evolving operational realities: scalable technologies designed for long-term impact, not short-term novelty." => ['es' => 'DigiTexia invierte continuamente en innovacion para construir soluciones digitales que respondan a las realidades operativas cambiantes de Africa: tecnologias escalables disenadas para impacto a largo plazo, no novedad de corto plazo.', 'it' => 'DigiTexia investe continuamente in innovazione per costruire soluzioni digitali che affrontano le realta operative africane in evoluzione: tecnologie scalabili progettate per impatto a lungo termine, non novita di breve periodo.', 'zh' => 'DigiTexia 持续投资创新，构建应对非洲不断变化运营现实的数字解决方案：为长期影响而设计的可扩展技术，而不是短期新奇功能。'],
];

$translations = ['es' => [], 'it' => [], 'zh' => []];
foreach ($base as $key => $values) {
    foreach ($translations as $locale => $_) {
        $translations[$locale][$key] = $values[$locale];
    }
}

foreach ($translations as $locale => $entries) {
    $path = $root . "/resources/lang/{$locale}.json";
    $json = json_decode(file_get_contents($path), true) ?: [];
    foreach ($entries as $key => $value) {
        $json[$key] = $value;
    }
    ksort($json, SORT_NATURAL | SORT_FLAG_CASE);
    file_put_contents($path, json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL);
}

echo "projects ES/IT/ZH translations fixed\n";
